### ISSUE TITLE
Integrate with a Kotlin linter  

### ISSUE THREAD

**Issue by u-ways** [propactive/propactive#15]
It would be nice to have a linter to keep the project as consistent as possible. A widely popular Kotlin linter is [Pinterest's ktlint](https://github.com/pinterest/ktlint). It has a built-in rule sets, formatter tasks, reporters, and allows extension with custom rule sets and reporters.

#### Requirements
- Set CI to run the linter after tests has passed. (must be a Makefile recipe)
- Provide an `.editorconfig` to allow IDE users adhere to the standards for a smoother dev experience.

Please see [the user guide](https://pinterest.github.io/ktlint/) for further details.

**Comment by doriancodes** [comment]
Hi! I would like to work on this issue :)

**Comment by u-ways** [comment]
Hello @doriancodes I am currently working on this, would you like to work on a similar issue: https://github.com/propactive/propactive-demo/issues/4 instead? Just leave a comment there and I will happily assign it to you.

**Comment by u-ways** [comment]
@doriancodes You can also have a look at other unassigned [CICD issues ](https://github.com/propactive/propactive/issues?q=is%3Aopen+label%3ACICD+no%3Aassignee) if interested.
