### ISSUE TITLE
`cd-workflow.yml` should not run `Publish-Deployment` job for non-sourcecode changes on merge

### ISSUE THREAD

**Issue by u-ways** [propactive/propactive#18]
Currently the CICD pipeline will publish a release for any merge/push to main branch. Sometimes that's not desirable (e.g. minor README.md updates, CICD pipelines updates...etc.) Therefore this ticket is to address this issue.

The underlying problem can be found here:
- [.github/workflows/cd-workflow.yml:42](../blob/master/.github/workflows/cd-workflow.yml#L42)

### Requirements
- Create a list of skippable files (i.e. `.github/*`, `/README.md`...etc.) or only whitelist jvm and plugin modules...?
- Review that `MANUAL-DEPLOYMENT.yml` pipeline is not impacted by these changes.

**Comment by aman2457** [comment]
Hey @u-ways , can you please assign me this issue?

**Comment by u-ways** [comment]
Hello @aman2457 , sure, this is now assigned to you :)

**Comment by u-ways** [comment]
Resolved by #38
