### ISSUE TITLE
Modify RELEASE pipeline to update README file with latest version available whenever a new version is released

### ISSUE THREAD

**Issue by u-ways** [propactive/propactive#6]
Whenever a new version is released, the README  the latest setup instructions should be updated to indicate the latest version to use. As such, given a README with:

```kts
plugins {
    id("io.github.propactive") version "1.1.1"
}

dependencies {
  implementation("io.github.propactive:propactive-jvm:1.1.1")
}
```

when version 1.1.2 is released, then the [RELEASE](https://github.com/propactive/propactive/blob/main/.github/workflows/RELEASE.yml) pipeline should update it to:

```kts
plugins {
    id("io.github.propactive") version "1.1.2"
}

dependencies {
  implementation("io.github.propactive:propactive-jvm:1.1.2")
}
```

**Comment by snapdgn** [comment]
Hey, mind if I take a stab at this?

**Comment by u-ways** [comment]
Hello @snapdgn , sure! This is now assigned to you.

**Comment by u-ways** [comment]
@snapdgn can these changes be applied to the https://github.com/propactive/propactive/blob/main/.github/workflows/RELEASE.yml workflow as a separate job, please?

**Comment by snapdgn** [comment]
> can these changes be applied to the https://github.com/propactive/propactive/blob/main/.github/workflows/RELEASE.yml workflow as a separate job, please?

sure.
