### ISSUE TITLE
Proofread README Documentation and Amend Typos

### ISSUE THREAD

**Issue by u-ways** [propactive/propactive#7]

**Comment by Mannuel25** [comment]
Hello @u-ways ,I'd love to take this up. Kindly assign it to me.

**Comment by u-ways** [comment]
> Hello @u-ways ,I'd love to take this up. Kindly assign it to me.

Hello @Mannuel25, awesome, sure! However this issue is labelled for hacktoberfest (see: https://hacktoberfest.com/participation/) and I have already made some unmerged README changes for 1.1.0 release. 

Would you be happy for me to ping you back on the first of October? (Start of Hacktoberfest)

**Comment by Mannuel25** [comment]
Sure, thanks!

**Comment by u-ways** [comment]
Hello @Mannuel25 , please feel free to pick this ticket whenever, I will have this reserved for you for the next few days as you asked for it first :)

**Comment by Mannuel25** [comment]
> Hello @Mannuel25 , please feel free to pick this ticket whenever, I will have this reserved for you for the next few days as you asked for it first :)

Sure, currently working on it. Thank you!
